- hosts: all
  strategy: free
  roles:
    - common

  tasks:

    - include_role:
        name: docker
        tasks_from: stack_teardown
      when: clean_install

    - name: Remove data directory (clean install)
      file: 
        path: '{{ data_dir }}'
        state: absent
      become: yes
      when: clean_install

    - include_role:
        name: common
        tasks_from: make_config_dir

    - include_role:
        name: common
        tasks_from: make_data_dir

    - name: Render loki.conf.j2 to {{ config_dir }}/fluent.conf
      template:
        src: loki.conf.j2
        dest: '{{ config_dir }}/fluent.conf'

    - include_role:
        name: docker
        tasks_from: stack_deploy

    - include_role:
        name: docker
        tasks_from: service_update
      vars:
        options: --force
        docker_service: collector
      when: not clean_install
